version: '3.8'

services:
  backend:
    image: alazzari93/commtrack-backend:latest
    container_name: commtrack_backend
    env_file:
      - ./backend/.env.prod
    volumes:
      - ./backend/sistema_comissoes/sistema_comissoes/db.sqlite3:/app/sistema_comissoes/sistema_comissoes/db.sqlite3
      - ./backend/sistema_comissoes/sistema_comissoes/static:/app/sistema_comissoes/sistema_comissoes/static
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: alazzari93/commtrack-frontend:latest
    container_name: commtrack_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

volumes:
  db_data:
