# Generated by Django 5.1.3 on 2024-11-06 02:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operadora', models.CharField(max_length=255)),
                ('comissionamento_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo', models.CharField(choices=[('PME', 'PME'), ('PF', 'Pessoa Física'), ('Adesão', 'Adesão')], max_length=50)),
                ('numero_parcelas', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('operadora', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField()),
                ('porcentagem_parcela', models.DecimalField(decimal_places=2, max_digits=6)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plano')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_proposta', models.CharField(max_length=100, unique=True)),
                ('valor_plano', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto_consultor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('taxa_plano', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_venda', models.DateField(default=django.utils.timezone.now)),
                ('data_vigencia', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consultor')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plano')),
            ],
        ),
        migrations.CreateModel(
            name='ControleDeRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_prevista_recebimento', models.DateField()),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Recebido', 'Recebido'), ('Não Recebido', 'Não Recebido')], default='Não Recebido', max_length=20)),
                ('numero_extrato', models.CharField(blank=True, max_length=100, null=True)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parcela')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venda')),
            ],
        ),
    ]
