# Generated by Django 5.1.3 on 2024-11-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cliente_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='taxa_plano',
        ),
        migrations.AddField(
            model_name='plano',
            name='taxa_plano_tipo',
            field=models.CharField(choices=[('Valor Fixo', 'Valor Fixo'), ('Porcentagem', 'Porcentagem')], default='Valor Fixo', max_length=20),
        ),
        migrations.AddField(
            model_name='plano',
            name='taxa_plano_valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
