name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Código
      uses: actions/checkout@v2

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login no Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build e Push Backend
      run: |
        docker build -t alazzari93/commtrack-backend:latest ./backend
        docker push alazzari93/commtrack-backend:latest

    - name: Build e Push Frontend
      run: |
        docker build -t alazzari93/commtrack-frontend:latest ./frontend
        docker push alazzari93/commtrack-frontend:latest

    - name: Deploy no Servidor AWS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.AWS_SERVER_IP }}
        username: ${{ secrets.AWS_SSH_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /var/www/CommTrack
          docker-compose pull
          docker-compose up -d
          docker-compose exec backend python manage.py migrate
          docker-compose exec backend python manage.py collectstatic --noinput
